import type { Config } from "tailwindcss";

// Catppuccin Macchiato palette
const macchiato = {
  base: "#24273a",
  mantle: "#1e2030",
  crust: "#181926",
  text: "#cad3f5",
  subtext1: "#b8c0e0",
  subtext0: "#a5adcb",
  overlay2: "#939ab7",
  overlay1: "#8087a2",
  overlay0: "#6e738d",
  surface2: "#5b6078",
  surface1: "#494d64",
  surface0: "#363a4f",
  rosewater: "#f4dbd6",
  flamingo: "#f0c6c6",
  pink: "#f5bde6",
  mauve: "#c6a0f6",
  red: "#ed8796",
  maroon: "#ee99a0",
  peach: "#f5a97f",
  yellow: "#eed49f",
  green: "#a6da95",
  teal: "#8bd5ca",
  sky: "#91d7e3",
  sapphire: "#7dc4e4",
  blue: "#8aadf4",
  lavender: "#b7bdf8",
};

// Catppuccin Latte palette
const latte = {
  base: "#eff1f5",
  mantle: "#e6e9ef",
  crust: "#dce0e8",
  text: "#4c4f69",
  subtext1: "#5c5f77",
  subtext0: "#6c6f85",
  overlay2: "#7c7f93",
  overlay1: "#8c8fa1",
  overlay0: "#9ca0b0",
  surface2: "#acb0be",
  surface1: "#bcc0cc",
  surface0: "#ccd0da",
  rosewater: "#dc8a78",
  flamingo: "#dd7878",
  pink: "#ea76cb",
  mauve: "#8839ef",
  red: "#d20f39",
  maroon: "#e64553",
  peach: "#fe640b",
  yellow: "#df8e1d",
  green: "#40a02b",
  teal: "#179299",
  sky: "#04a5e5",
  sapphire: "#209fb5",
  blue: "#1e66f5",
  lavender: "#7287fd",
};

export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app/**/*.vue",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        macchiato: {
          "color-scheme": "dark",
          primary: macchiato.mauve,
          "primary-content": macchiato.crust,
          secondary: macchiato.surface0,
          "secondary-content": macchiato.text,
          accent: macchiato.rosewater,
          "accent-content": macchiato.crust,
          neutral: macchiato.overlay1,
          "neutral-content": macchiato.crust,
          "base-100": macchiato.base,
          "base-200": macchiato.mantle,
          "base-300": macchiato.crust,
          "base-content": macchiato.text,
          info: macchiato.sapphire,
          "info-content": macchiato.crust,
          success: macchiato.green,
          "success-content": macchiato.crust,
          warning: macchiato.yellow,
          "warning-content": macchiato.crust,
          error: macchiato.red,
          "error-content": macchiato.crust,
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
      {
        latte: {
          "color-scheme": "light",
          primary: latte.mauve,
          "primary-content": latte.base,
          secondary: latte.surface0,
          "secondary-content": latte.text,
          accent: latte.rosewater,
          "accent-content": latte.base,
          neutral: latte.overlay1,
          "neutral-content": latte.base,
          "base-100": latte.base,
          "base-200": latte.mantle,
          "base-300": latte.crust,
          "base-content": latte.text,
          info: latte.sapphire,
          "info-content": latte.base,
          success: latte.green,
          "success-content": latte.base,
          warning: latte.yellow,
          "warning-content": latte.base,
          error: latte.red,
          "error-content": latte.base,
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
} satisfies Config;
